### ISSUE TITLE
GitHub Repository description unclear

### ISSUE THREAD

**Issue by MichaelGooden** [zfcampus/zf-development-mode#21]
The GitHub Repository description should be updated to reflect that this can be used with both ZF2 zend-mvc and ZF3 zend-mvc.

Just had someone in IRC ask whether it worked with ZF3 as the description on GitHub was unclear.

**Comment by weierophinney** [comment]
Fixed on develop; thanks for opening the issue, @MichaelGooden !

**Comment by MichaelGooden** [comment]
Not quite fixed :p

I am referring specifically to the GitHub Repository Description field in the repository settings (also why this was just an issue and not a pull request, only repository members have access to the settings tab). It currently reads: "ZF2 development mode module"
